# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImpedanceInputWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImpedancesInputWindow(object):
    def setupUi(self, ImpedancesInputWindow):
        ImpedancesInputWindow.setObjectName("ImpedancesInputWindow")
        ImpedancesInputWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(ImpedancesInputWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(260, 300, 111, 51))
        self.NextButton.setObjectName("NextButton")
        self.Impedancelabel = QtWidgets.QLabel(self.centralwidget)
        self.Impedancelabel.setGeometry(QtCore.QRect(0, 110, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Impedancelabel.setFont(font)
        self.Impedancelabel.setScaledContents(False)
        self.Impedancelabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Impedancelabel.setWordWrap(False)
        self.Impedancelabel.setObjectName("Impedancelabel")
        self.ImpedanceInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ImpedanceInput.setGeometry(QtCore.QRect(330, 130, 113, 20))
        self.ImpedanceInput.setAlignment(QtCore.Qt.AlignCenter)
        self.ImpedanceInput.setObjectName("ImpedanceInput")
        self.LengthInput = QtWidgets.QLineEdit(self.centralwidget)
        self.LengthInput.setGeometry(QtCore.QRect(330, 180, 113, 20))
        self.LengthInput.setAlignment(QtCore.Qt.AlignCenter)
        self.LengthInput.setObjectName("LengthInput")
        self.Lengthlabel = QtWidgets.QLabel(self.centralwidget)
        self.Lengthlabel.setGeometry(QtCore.QRect(0, 160, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Lengthlabel.setFont(font)
        self.Lengthlabel.setScaledContents(False)
        self.Lengthlabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Lengthlabel.setWordWrap(False)
        self.Lengthlabel.setObjectName("Lengthlabel")
        self.WelcomeButton = QtWidgets.QPushButton(self.centralwidget)
        self.WelcomeButton.setGeometry(QtCore.QRect(260, 370, 111, 51))
        self.WelcomeButton.setObjectName("WelcomeButton")
        ImpedancesInputWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImpedancesInputWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        ImpedancesInputWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImpedancesInputWindow)
        self.statusbar.setObjectName("statusbar")
        ImpedancesInputWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ImpedancesInputWindow)
        QtCore.QMetaObject.connectSlotsByName(ImpedancesInputWindow)

    def retranslateUi(self, ImpedancesInputWindow):
        _translate = QtCore.QCoreApplication.translate
        ImpedancesInputWindow.setWindowTitle(_translate("ImpedancesInputWindow", "MainWindow"))
        self.NextButton.setText(_translate("ImpedancesInputWindow", "Next"))
        self.Impedancelabel.setText(_translate("ImpedancesInputWindow", "Enter impedance of section 1"))
        self.Lengthlabel.setText(_translate("ImpedancesInputWindow", "Enter length of section 1"))
        self.WelcomeButton.setText(_translate("ImpedancesInputWindow", "Welcome"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImpedancesInputWindow = QtWidgets.QMainWindow()
    ui = Ui_ImpedancesInputWindow()
    ui.setupUi(ImpedancesInputWindow)
    ImpedancesInputWindow.show()
    sys.exit(app.exec_())
