# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lattice_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

i=1
impedanceArray=[]
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(260, 210, 111, 51))
        self.nextButton.setObjectName("nextButton")
        self.Impedancelabel = QtWidgets.QLabel(self.centralwidget)
        self.Impedancelabel.setGeometry(QtCore.QRect(0, 110, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Impedancelabel.setFont(font)
        self.Impedancelabel.setScaledContents(False)
        self.Impedancelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Impedancelabel.setWordWrap(False)
        self.Impedancelabel.setObjectName("Impedancelabel")
        self.Finish = QtWidgets.QPushButton(self.centralwidget)
        self.Finish.setGeometry(QtCore.QRect(260, 280, 111, 51))
        self.Finish.setObjectName("Finish")
        self.impedanceInput = QtWidgets.QLineEdit(self.centralwidget)
        self.impedanceInput.setGeometry(QtCore.QRect(330, 130, 113, 20))
        self.impedanceInput.setAlignment(QtCore.Qt.AlignCenter)
        self.impedanceInput.setObjectName("impedanceInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.Impedancelabel.setText(_translate("MainWindow", "Enter impedance of section 1"))
        self.Finish.setText(_translate("MainWindow", "Finish"))

        self.nextButton.clicked.connect(self.clicked_next)
        self.Finish.clicked.connect(self.clicked_finish)

    def clicked_next(self):
        global i
        i+=1
        self.Impedancelabel.setText("Enter impedance of section "+str(i))
        text = self.impedanceInput.text()
        impedanceArray.append(float(text))
        self.impedanceInput.clear()

    def clicked_finish(self):
        print(impedanceArray)  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
